name: CI

permissions:
  contents: write
  packages: write

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    uses: Vempain/vempain-workflows/.github/workflows/website.yaml@main
    with:
      backend_image: ghcr.io/vempain/vempain-site-backend
      frontend_image: ghcr.io/vempain/vempain-site-frontend
    secrets: inherit
